Update ci-cd.yaml

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -31,9 +31,12 @@ jobs:
 
       - name: Set up Helm
         uses: azure/setup-helm@v1
+        with:
+          version: 'latest' # Ensure you're using the latest Helm version
 
       - name: Install helm-s3 plugin
-        run: helm plugin install https://github.com/hypnoglow/helm-s3.git
+        run: |
+          helm plugin install https://github.com/hypnoglow/helm-s3.git || true # The '|| true' ensures that if the plugin is already installed, the script doesn't fail.
       
       - name: Package Helm chart
         run: helm package /home/ubuntu/color-grid -d . --version 0.1.0 --app-version ${{ github.sha }}
